import type { Metadata } from 'next';
import StyledJsxRegistry from './registry';
import { GluestackUIProvider } from '@/components/ui/gluestack-ui-provider';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <GluestackUIProvider mode="light">
            <div>header</div>
            <div>{children}</div>
            <div>footer</div>
          </GluestackUIProvider>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
